### ISSUE TITLE
local pre-commit hooks

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-gfmap#1]
https://github.com/Open-EO/openeo-gfmap/blob/14fc5111d25b7f3f82231cf401631241b4c7bb6a/.pre-commit-config.yaml#L31

Why are all these hooks local? As far as I know you can get isort, black, etc from regular repos

**Comment by soxofaan** [comment]
e.g. I had to disable some of these hooks in 438fc8f to be able to commit again

**Comment by GriffinBabe** [comment]
pre-commit now works
