### ISSUE TITLE
Investigate automated orbit selection for Sentinel-1 in extraction jobs

### ISSUE THREAD

**Issue by kvantricht** [Open-EO/openeo-gfmap#10]
We want to know if there are more ASCENDING or DESCENDING S1 products for a certain spatio-temporal extent, and then only choose the majority case for the processing.

We can query the catalogue before running the job, but unfortunately this does not take into account the footprint of each individual product (the spatial extent might be in the intersection of the product and another orbit).

@jdries Do you know if there is a way of checking that outside or within an OpenEO job?

**Comment by kvantricht** [comment]
@jdries any ideas on this one?

**Comment by jdries** [comment]
I would think that the catalog does correctly take the footprint into account? Or it is at least correctly stored in the metadata, so we can probably retrieve all available products and then only retain the ones with a proper intersection?

**Comment by kvantricht** [comment]
Catalogue query by gfmap, get the geometries and then find out (geopandas) to see which orbit has full overlap.

**Comment by GriffinBabe** [comment]
It's possible to see the entire footprint of each product and how it intersects with the bounding box

![s1_ascending_descending_query](https://github.com/Open-EO/openeo-gfmap/assets/23267782/4e21bd5c-d705-4393-8d0f-1001ae8f864e)

@kvantricht I implemented an util function that queries on CDSE the footprint of available products for ASCENDING and DESCENDING and computes for both if the area of interest (AOI) is fully covered, as well as the accumulated surface of intersection between the products and the AOI.

One issue I see with this method is that some zones of one AOI might be less equally covered than others using this method. A method that computes which between ASCENDING and DESCENDING orbit states has a more homogeneous coverage could be done, although it is not trivial and I don't think it's a priority.

I'm opening a PR with the util function
