### ISSUE TITLE
Change BAP implementation from UDF to UDP

### ISSUE THREAD

**Issue by VincentVerelst** [Open-EO/openeo-gfmap#105]
The current implementation of the best-available-pixel (BAP) compositing is based on a UDF. Since then, the algorithm has been updated to be more accurate and only makes use of pre-defined OpenEO processes, see https://github.com/Open-EO/openeo-community-examples/blob/main/python/RankComposites/bap_composite.ipynb

It would be good to also update the BAP implementation here.

**Comment by HansVRP** [comment]
should we consider turning BAP in a standardized openEO process itself? 

Maybe good to discuss with Jeroen.
