### ISSUE TITLE
Update orbit selection strategy

### ISSUE THREAD

**Issue by GriffinBabe** [Open-EO/openeo-gfmap#154]
At the moment, S1 orbits is being selected with the maximum accumulated area overlapping between the spatial extent and the available products in the catalogue, however this does not take into account edge cases such as:
- [x] Long periods without any observations.
- [x] To be filled @kvantricht

**Comment by kvantricht** [comment]
Reproduce by:

`(35.85799, 49.705688, 36.039682, 49.797363)`
`temporal_extent = TemporalContext('2018-07-30', '2020-01-31')`

chooses ascending though it has huge temporal gap at the start

**Comment by kvantricht** [comment]
https://github.com/Open-EO/openeo-gfmap/pull/158 closes this.
