### ISSUE TITLE
split_job_hex not working

### ISSUE THREAD

**Issue by HansVRP** [Open-EO/openeo-gfmap#166]
h3.geo_to_h3 seems to be no longer supported

**Comment by HansVRP** [comment]
I believe the function was renamed to latlng_to_cell, so it would be a small fix.

In addition there would be need of an integration test to ensure this function remains stable. 

Thoughts @VincentVerelst ?

**Comment by VincentVerelst** [comment]
This seems to be a breaking API change in h3 from v4.0.0 onwards. 

In our dependencies we don't specify any specific version of h3: https://github.com/Open-EO/openeo-gfmap/blob/main/pyproject.toml#L41

I propose the small fix and then pin our h3 dependency to v.4.0.0 (or a later one). Thoughts?

**Comment by HansVRP** [comment]
Sounds good.

**Comment by HansVRP** [comment]
Can you take this small bugfix up?
