### ISSUE TITLE
Generate a STAC catalogue after a series of job is finished

### ISSUE THREAD

**Issue by kvantricht** [Open-EO/openeo-gfmap#18]
Once a OpenEO-GFMAp task is finished, leave the option to create a STAC catalogue listing all the generated products.

By task, I mean once all the related jobs from GFMAP are finished: for example, extraction task is split in many jobs. The end of the task means the end of all the jobs and their related post-processing tasks (Issue https://github.com/Open-EO/openeo-gfmap/issues/11)

**Comment by jdries** [comment]
This can also be covered by this openEO feature:
https://github.com/Open-EO/openeo-geopyspark-driver/issues/606

**Comment by VincentVerelst** [comment]
Currently, one STAC collection is generated for a series of batch jobs. Next steps:

- Enrich the collection metadata: https://worldcereal.github.io/worldcereal-documentation/design/extractions.html
- Add geometry and bbox to the netCDF item metadata: https://github.com/Open-EO/openeo-geopyspark-driver/issues/689

**Comment by GriffinBabe** [comment]
Merged #52
