### ISSUE TITLE
query_cdse_catalogue fails for point geometries

### ISSUE THREAD

**Issue by VincentVerelst** [Open-EO/openeo-gfmap#180]
`query_cdse_catalogue` will return a 400 if a featurecollection contains only one point. The API expects a bounding box as input. Possibly the quickest fix would be to perform a buffer on the point right before the query, to make sure we always have a bounding box.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the _query_cdse_catalogue function to add a buffer around a single point, ensuring that the CDSE API always receives a bounding box. This fixes the issue where the API returns a 400 error for feature collections containing only one point.

You can review changes in this commit: https://github.com/lkilu6456546/Open-EO-openeo-gfmap-180/commit/fde694a01d563ad686b5838a7f9031fb4819fc6c.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
