### ISSUE TITLE
Sample notebook for landcover classification

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-gfmap#46]
A project is requesting an update of this usecase:
https://docs.openeo.cloud/usecases/landcover/

As this is more of a production project, I suggest to use GFMap for it.
Also need some specific updates:
- use best available pixel for compositing
- feature list to be provided by project
- eventually needs to run on cdse

I'm also considering a design where we build a database of extractions, so we can run multiple trainings runs. (The original usecase did extraction and training in one job, which is nice but does not support a large amount of extractions.)

**Comment by VictorVerhaert** [comment]
Extraction and inference notebooks have been made.

TODO

- [ ] add DEM as a feature, waiting for feedback from gisat on how to do this.
- [ ] (optional) add BAP 
- [ ] optimize PG for the extraction (WIP)

**Comment by HansVRP** [comment]
For now simple masking is enough. 

Leave it like this. Spent 1 or 2 days on optimization. 

Follow up ticket on including BAP

**Comment by VictorVerhaert** [comment]
Closing this issue. I will create new issues when they arise
