### ISSUE TITLE
Investigate memory issue in OpenEO

### ISSUE THREAD

**Issue by kvantricht** [Open-EO/openeo-gfmap#50]
As mentioned by @GriffinBabe, there's a known memory issue in OpenEO to be solved which rapidly increases the required memory by a job because in one step of the extraction process, temporal dimension blows up.

Jeroen, can you check this?

**Comment by jdries** [comment]
@GriffinBabe  Can you provide details? Or did you already do that somewhere?
I remember one occasion a couple of weeks ago, but not sure if we're talking about that one?

**Comment by jdries** [comment]
@GriffinBabe  we have sprint planning tomorrow, but would require more info for this one.

**Comment by jdries** [comment]
Closing this one, I brought memory down to 2.5GB per executor, of course not clear if it was this issue...
