### ISSUE TITLE
Generate one large STAC collection after all separate source jobs have finished

### ISSUE THREAD

**Issue by kvantricht** [Open-EO/openeo-gfmap#51]
Once separate GFMAP jobs are done per satellite source, we need to create one overarching STAC collection containing items that hold the metadata of all the extracted sources.
- where does this happen?
- how does this happen?

**Comment by GriffinBabe** [comment]
@VincentVerelst the path construction for the samples is defined in the following meeting notes 

https://vitoresearch.sharepoint.com/sites/21717-ccn-world-cereal/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=09MIZM&OR=Teams%2DHL&CT=1710759776079&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0OS8yNDAyMDIwNTUxNiIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&cid=33cbc2b7%2Ded02%2D4753%2D81fd%2Dbfa478e989e1&RootFolder=%2Fsites%2F21717%2Dccn%2Dworld%2Dcereal%2FShared%20Documents%2FGeneral%2FMeetings%2F20240313%2DPM1%2FBreakout%20sessions&FolderCTID=0x012000A0D814B2FE25994FA20A82ACDCBA1577

**Comment by kvantricht** [comment]
For now it's decided as not needed and to keep the individual collections which can be loaded resulting in `merge_cube` operations on the fly.
