### ISSUE TITLE
Create extractor for other data collections

### ISSUE THREAD

**Issue by gutkinn** [Open-EO/openeo-gfmap#53]
Implement an extractor for other datasets (dem and meteo) following the format of S1/S2 extractors

**Comment by VictorVerhaert** [comment]
An extractor that uses load_stac would allow for fetching specific collections like HRL VPP.

**Comment by GriffinBabe** [comment]
@gutkinn could you push that branch with your DEM and METOE extractors?

**Comment by GriffinBabe** [comment]
Closed by #95 
Thanks @gutkinn

**Comment by VictorVerhaert** [comment]
Currenty this generic extractor does not allow for fetching collections other than AGERA5 and COPERNICUS_30. Is there a way of trying a default approach for other collections?

The only difference is the band mapping, which we could naivly ignore and throw a warning that some functionality will be limited?
