### ISSUE TITLE
Double-check SCL dilation parameters wrt input resolution

### ISSUE THREAD

**Issue by kvantricht** [Open-EO/openeo-gfmap#56]
Parameters of the process need to be set with respect to the input resolution of the imagery. At the moment it's unclear of the process works at 20m or at 10m. This needs to be investigated and clarified.

**Comment by kvantricht** [comment]
Recommended approach is to enforce resample spatial to 10m of SCL before applying the mask_scl_dilation.
To be checked by @soxofaan if this adds unnecessary overhead.

**Comment by soxofaan** [comment]
> To be checked by @soxofaan if this adds unnecessary overhead.

as discussed, @jdries is taking over this ticket

**Comment by kvantricht** [comment]
Closed because of lack of follow-up and half of datasets already processed. Pray for the best...
