### ISSUE TITLE
POINT extraction with FeatureColleciton containing POINT's

### ISSUE THREAD

**Issue by VictorVerhaert** [Open-EO/openeo-gfmap#59]
This causes an error on the openeo backend because the S1 fetcher applies a `filter_spatial` on the loaded collection.
I was able to fix this bug locally by changing 
https://github.com/Open-EO/openeo-gfmap/blob/63541e9a841f24307059fa5cac09cb053acbd0ec/src/openeo_gfmap/fetching/s1.py#L79-L80
to
```
if fetch_type is not FetchType.POINT and isinstance(spatial_extent, GeoJSON):
    ...
```
The S2 fetches does not do this so this does not pose a problem there.

**Comment by GriffinBabe** [comment]
Closed by #63
