### ISSUE TITLE
Optimize S2 data loading by computing and applying (conservative) cloud mask

### ISSUE THREAD

**Issue by kvantricht** [Open-EO/openeo-gfmap#61]

**Comment by GriffinBabe** [comment]
We would like to exclude entire observations depending on the amount of pixels marked as HIGH_PROBA_CLOUDS in the SCL layer. So far we implemented an UDF that directly generates a mask either covering the entire observation, or being totally empty (only 0s). We managed to run the UDF locally but running on open-eo poses a problem:

- Running using `apply_neighborhood` requires specifying an area, and padded zones of the array can cause problems on the computation of the occurrence of HIGH_PROBA_PIXELS. Does OpenEO has a standard value for padded pixels? This way we can try to ignore those values. Also the output mask needs to be matching the input size. 
- Running using `apply` does it pixel-wise, so running the UDF like so is not possible.
- Additionally, how can we make this work when it comes with the extraction of samples? Here especially, we are running extractions on 64x64 pixel tiles.

Minimal example is:
```
import openeo
from tempfile import NamedTemporaryFile
from shapely import box
from shapely.geometry import mapping

from openeo.udf import execute_local_udf, XarrayDataCube
from openeo import UDF


connection = openeo.connect('https://openeo.dataspace.copernicus.eu').authenticate_oidc()

spatial_extent = mapping(
    box(4.591687083409023, 51.11455367032077, 4.607750156043775, 51.129320859000856)
)

cube = connection.load_collection(
    "SENTINEL2_L2A",
    spatial_extent=spatial_extent,
    temporal_extent=["2022-01-01", "2022-03-01"],
    bands=["B04", "B03", "B02", "SCL"]
)

mask = cube.filter_bands(["SCL"]).apply_neighborhood(
    process=UDF.from_file("../src/openeo_gfmap/preprocessing/udf_cldmask.py", context={}),
    size=[
        {"dimension": "x", "unit": "px", "value": 1024},
        {"dimension": "y", "unit": "px", "value": 1024},
    ],
    overlap=[],
).rename_labels("bands", ["MASK"])

cube = cube.merge_cubes(mask)

job = cube.create_job(
    title="Full cldmask test",
    out_format="netcdf",
)

job.start_and_wait()
```

With udf_cldmask.py being:
```
import numpy as np
import xarray as xr
from openeo.udf import XarrayDataCube


def apply_datacube(cube: XarrayDataCube, context: dict) -> XarrayDataCube:
    """
    Computes a cloud mask covering a full observation or nothing depending on the percentage of
    high probability cloud pixels. If the amount of before mentioned pixels is higher than 95%,
    then returns a mask covering the whole observation, otherwise returns an empty mask.
    """
    array = cube.get_array().transpose("t", "bands", "y", "x")

    output_array = np.zeros(
        shape=(array.shape[0], 1, array.shape[2], array.shape[3]),
        dtype=np.uint8
    )

    for i in range(array.shape[0]):
        high_proba_count = (
            (array[i] == 9) * 1
        ).sum()
        high_proba_percentage = high_proba_count / (array.shape[2] * array.shape[3])

        if high_proba_percentage > 0.95:
            output_array[i] = 1
            
    output_array = xr.DataArray(
        output_array,
        dims=["t", "bands", "y", "x"],
        coords={
            "t": array.t,
            "bands": ["mask"],
            "y": array.y,
            "x": array.x,
        },
    )

    return XarrayDataCube(output_array)
```

**Comment by jdries** [comment]
I see two options in general:
- using apply_polygon + the UDF
- using aggregate_spatial on the scl mask to count number of clouded pixels, then convert this count back into a raster using vector_to_raster, and then applying a threshold to turn count into binary mask again

We would need to check performance of both options. Aggregate_spatial has the advantage that it does not require tiles to be grouped by polygon, and also not requiring UDF. 
@JeroenVerstraelen  Do you think the aggregate_spatial approach would already work, based on latest improvements?

**Comment by jdries** [comment]
By default it will be NaN, but the process has a 'mask_value' parameter for user-defined padding:
https://processes.openeo.org/#apply_polygon

**Comment by jdries** [comment]
The option with apply_polygon would process full timeseries per polygon, which is a bit heavy.
Hence we're looking at option 2. I already have basic code, but we're finishing up a backend feature to make it work. (It was already in progress for another usecase.)

I think the code for that option would look like this:

```
    cube = connection.load_collection("SENTINEL2_L2A", temporal_extent=("2022-03-01", "2022-09-20"),
                                      spatial_extent=extent, bands=["SCL"], max_cloud_cover=85)
    cube = (cube ==9) | (cube ==8)
    mask = cube.polygonal_mean_timeseries(poly).vector_to_raster(cube).apply(lambda x:x>0.5)

    bands = connection.load_collection("SENTINEL2_L2A", temporal_extent=("2022-03-01", "2022-09-20"),
        spatial_extent = extent, bands = ["B02"],max_cloud_cover=85).mask(mask)
```

**Comment by GriffinBabe** [comment]
@jdries any update on this one?

**Comment by jdries** [comment]
@JeroenVerstraelen or @VincentVerelst  can you post here when the vector_to_raster from aggregate_spatial works?

**Comment by soxofaan** [comment]
As I tried to explain in the  meeting today, there might be an approximating alternative too, that does not depend on experimental features like vector_to_raster, but just `apply_kernel`.

In (pseudo)code:
```python
scl_band = connection.load_collection("SENTINEL2_L2A", bands=["SCL"], ...).band("SCL")
clouds = (scl_band ==9) | (scl_band ==8)
cloud_mask = clouds.apply_kernel(kernel) > threshold

cube = connection.load_collection("SENTINEL2_L2A", bands=["B02"], ....).mask(cloud_mask)
```

The trick here is to approximate `aggregate_spatial(polygons).vector_to_raster()`  with `apply_kernel(kernel)`.
For example if the kernel is a normalized [disk/rectangle](https://scikit-image.org/docs/stable/auto_examples/numpy_operations/plot_structuring_elements.html) with large enough support (e.g. order of patch size I think), all pixels in the blurred output will be close to the fraction of cloud pixels in that area. If you apply a thresholding, the result should be pretty close to the exact result of `aggregate_spatial(polygons).vector_to_raster()`. 

I hope this explanation makes some sense

**Comment by GriffinBabe** [comment]
I will close this issue for the moment, as this issue is taking us too much time and it is still uncertain how much optimization it will bring
