### ISSUE TITLE
Scale S1 data linearly from float32 power values to uint16

### ISSUE THREAD

**Issue by GriffinBabe** [Open-EO/openeo-gfmap#70]
Optimization of memory by scaling sentinel-1 power values to uint16

- [x] Perform data scaling in the data fetching phase
- [ ] Provide utils to retrieve data in power values or in dB within the Feature Computers

**Comment by jdries** [comment]
the additional check in isCreo is still relevant normally. Orfeo has not yet received a fix for these low values as far as I know.
sar_backscatter indeed always returns power values
