### ISSUE TITLE
Use load_stac to read in rasterized extractions

### ISSUE THREAD

**Issue by VincentVerelst** [Open-EO/openeo-gfmap#85]
After the extractions we will have 4 overarching STAC collections. (S1, S2, Agera5 and ground truth). 

- [x] Make sure `load_stac` is able to load in each STAC collection. The assets are netcdf's with time series
- [x] Make sure the backend and Python client have the band information (needed for feature computation later)
- [x] Merge the 4 collections with `merge_cubes` 

This is a subissue of https://github.com/Open-EO/openeo-gfmap/issues/4

**Comment by jdries** [comment]
@VincentVerelst  make sure to try on openeo-dev. I fixed a very similar issue for you last week I believe, but not sure if we promoted the fix to prod already.

**Comment by VincentVerelst** [comment]
Confirmed, `load_stac` works on openeo-dev. Two important notes:

- Not working on prod yet
- Also need to wait for next release of the Python client to have the band information also on the client side. Currently need to use a local checkout of the python client master branch.

**Comment by VincentVerelst** [comment]
Currently getting _geotrellis.raster.gdal.MalformedDataTypeException: Unable to determine NoData value. GDAL Exception Code: 4._ when trying to load the ground truth data (netCDF without time dimension)

Loading the S2 data (netCDF with time dimension) works. 

Both on backend openeo-dev.vito.be

**Comment by VincentVerelst** [comment]
Currently blocked by https://github.com/Open-EO/openeo-geotrellis-extensions/issues/282

**Comment by VincentVerelst** [comment]
with https://github.com/Open-EO/openeo-gfmap/pull/99 it should be able to also read in the ground truth netCDF with `load_stac`
