### ISSUE TITLE
Save computed features to geoparquet

### ISSUE THREAD

**Issue by VincentVerelst** [Open-EO/openeo-gfmap#87]
Support the saving of a point feature extraction to a geoparquet file
'Features' in this case is preprocessed timeseries, not the presto features.

**Comment by GriffinBabe** [comment]
There is already a code snippet that could be useful for this issue:
https://github.com/Open-EO/openeo-gfmap/blob/main/src/openeo_gfmap/utils/build_df.py#L13

This function reads the json output of an openeo-job and generates a dataframe for that. Not sure if this is exactly what you need though
