### ISSUE TITLE
Setup Jenkins status to GitHub branches

### ISSUE THREAD

**Issue by GriffinBabe** [Open-EO/openeo-gfmap#9]
See with Jeroen Verstraelen

**Comment by soxofaan** [comment]
@JeroenVerstraelen

**Comment by kvantricht** [comment]
Could we also (or instead) use Github actions?

**Comment by soxofaan** [comment]
If I remember correctly: an issue is to be able to do authentication, involving a (client) secret, which we have tooling for in Jenkins. It's probably also possible to set something up in Github actions, but that will take a lot more time to figure out I guess

**Comment by GriffinBabe** [comment]
@soxofaan How can I setup the authentication on Jenkins for `authenticate_oidc`? So far Jenkins builds are failing as unit tests cannot authenticate

**Comment by soxofaan** [comment]
hmm yes, the annoying thing is that you want to connect to multiple backends (VITO, CDSE, ...), which makes things less straightforward

**Comment by soxofaan** [comment]
> So far Jenkins builds are failing as unit tests cannot authenticate

As far as I can see, the jenkins run is broken because the test collection fails, it doesn't even reach trying to create a connection. 

e.g. I see this

```
Error Message

collection failure

Stacktrace

ImportError while importing test module '/var/lib/jenkins/workspace/openeo-gfmap_issue9-jenkins-auth/tests/test_openeo_gfmap/test_s1_fetchers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_openeo_gfmap/test_s1_fetchers.py:27: in <module>
    from .test_s2_fetchers import (
E   ImportError: attempted relative import with no known parent package
```

**Comment by soxofaan** [comment]
FYI: I made an initial step in 1fb7b49 to setup jenkins auth, but as mentioned above (and #13)  the whole test suite even fails the collection phase, so I can not iterate on getting auth in shape

**Comment by kvantricht** [comment]
@GriffinBabe is that something you also get when running `pytest` locally?

**Comment by soxofaan** [comment]
I get that error too when running `pytest` locally FYI

**Comment by soxofaan** [comment]
Import issues mentioned above have been resolved now

I've also set up a bunch of code quality things that do not require auth or openeo processing (linting, formatting, ...) under #16

**Comment by kvantricht** [comment]
@soxofaan do you know the status of the jenkins pipelines? If we want to get going with a first UDF in the `worldcereal-classification` repo making use of GFMAP functionality, then we need a working pipeline with automated builds pushed to artifactory so we can install it as a depenency.

**Comment by soxofaan** [comment]
The Terrascope auth seems to work in the feature branch I'm working in
The tests take very long however (by nature), so it's cumbersome to iterate and getting all the necessary things in place

**Comment by soxofaan** [comment]
I think I now got the auth stuff working with #30 
tests in jenkins now get beyond auth for both Terrascope and CDSE, but some still fail for other reasons, but that is for other tickets.

going to close this one for now
