### ISSUE TITLE
Verify accounting for WorldCereal workflows

### ISSUE THREAD

**Issue by kvantricht** [Open-EO/openeo-gfmap#91]
Before doing mass extractions we have to find out how accounting works.
Assumption: should be done for now for the service account.

**Comment by GriffinBabe** [comment]
@soxofaan Any update on this one? It is becoming a pretty urgent issue as we want to start extracting in May

**Comment by jdries** [comment]
@GriffinBabe yes, we discussed this.
Basically you will just want to start extractions, preferably with a gradual ramp-up, using the service account.
We will then also want to make a nor request to have enough credits.
Any other questions?

**Comment by GriffinBabe** [comment]
How can I access the service account? Is it something I need to setup on my own account or do I need to use specific credentials?

**Comment by soxofaan** [comment]
Using a service account is authenticating like this:

```
connection.authenticate_oidc_client_credentials(
    client_id=client_id,
    client_secret=client_secret,
)
```
the client_id I prepared is `openeo-worldcereal-service-account` and the secret is in the VITO vault. I don't want to share too much about that here publicly. How to actually get it and responsibly handle that secret depends a bit on how and in what context you will be running the workflow. 
Have you already worked with the VITO Vault before and do you (know if you) have access?

**Comment by soxofaan** [comment]
I just ran job `j-24050764b4e34222a20620a4b7f16008` against `openeo.dataspace.copernicus.eu` with service account `openeo-worldcereal-service-account` (which is associated with user id `bb97dfc9-f1cc-4b8a-a1be-8a75d4cca3a9`)  and I see that credits are being logged for it in the marketplace (CDSE prod):

![image](https://github.com/Open-EO/openeo-gfmap/assets/44946/08a2247d-1409-4dec-8be0-53733672778d)

**Comment by soxofaan** [comment]
In general, I see already multiple billing events for that user `bb97dfc9-f1cc-4b8a-a1be-8a75d4cca3a9`:

![image](https://github.com/Open-EO/openeo-gfmap/assets/44946/75c83c29-ee1d-4738-8ec4-17e0f8b95850)

**Comment by JanssenBrm** [comment]
The accounting for this account is now done on the "personal" organization of the service account, which currently has 6358 remaining credits. However, I would suggest adding @kvantricht  and @GriffinBabe to this organization so that they can also check the current credit balance. Would this be OK?

**Comment by kvantricht** [comment]
@VincentVerelst for sure too as he's following up on the extractions. Still no word from NoR people so given that these credits seem to run out really fast, we'll have to find some solution soon.

**Comment by JanssenBrm** [comment]
I've added @kvantricht, @GriffinBabe and @VincentVerelst  as organization owners to the WorldCereal organization. Information on how to check the credits is available on https://documentation.dataspace.copernicus.eu/Applications/AlgorithmPlaza.html#managing-your-account. You can simply change your current linked organization to WorldCereal and navigate to the billing page. **Important:** remember to switch back to another organization. If you don't do this, credits will be deducted from the WorldCereal account when using your personal account for openEO processing.

As organization owners, you can invite other people to join as well. More information is available at https://documentation.dataspace.copernicus.eu/Applications/PlazaDetails/ManageOrg.html
